CREATE USER 'yorisoi_user'@'localhost' IDENTIFIED BY 'p@ssw0rd';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON db_name.* TO 'kimochi_user'@'localhost';

CREATE USER 'yorisoi_user'@'%' IDENTIFIED BY 'p@ssw0rd';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON db_name.* TO 'kimochi_user'@'%';
